githubs:

  - host: ghe.corp.yahoo.co.jp
    env: ACCESS_TOKEN_GHE
    api_base: https://ghe.corp.yahoo.co.jp/api/v3
    raw_base: https://raw.ghe.corp.yahoo.co.jp

  - host: git.corp.yahoo.co.jp
    env: ACCESS_TOKEN_GIT
    api_base: https://git.corp.yahoo.co.jp/api/v3
    raw_base: https://raw.git.corp.yahoo.co.jp

  - host: partner.git.corp.yahoo.co.jp
    env: ACCESS_TOKEN_PARTNER
    api_base: https://partner.git.corp.yahoo.co.jp/api/v3
    raw_base: https://partner.git.corp.yahoo.co.jp/raw

secrets:
  - name: sd_user_token_cd
    env: SD_USER_TOKEN_CD
  - name: sd_user_token_next
    env: SD_USER_TOKEN_NEXT
  - name: dragon_access_key
    env: DRAGON_ACCESS_KEY
  - name: dragon_secret_access_key
    env: DRAGON_SECRET_ACCESS_KEY
