jobs:

  pr:
    image: cd.docker-registry.corp.yahoo.co.jp:4443/approduce/hosted-danger-sd-image:latest
    requires: [~pr]
    steps:
      - format: |
          crystal tool format --check &> /dev/null
          ret_code=$?

          if [ 0 -ne $ret_code ]; then
              echo 'Please formatting the codes. ('$ret_code')'
              exit $ret_code
          else
              echo 'Success!'
          fi
      - build: |
          shards build
      - test: |
          crystal spec

  commit:
    image: cd.docker-registry.corp.yahoo.co.jp:4443/approduce/hosted-danger-sd-image:latest
    requires: [~commit]
    steps:
      - build: |
          shards build
      - test: |
          crystal spec

  publish-image:
    template: docker/publish@stable
    environment:
      REPO_NAME: approduce
      IMAGE_NAME: hosted-danger-image
    requires: [commit]
    steps:
      - prebuild_image: tools/setenv
    secrets:
      - ACCESS_TOKEN_GHE
      - ACCESS_TOKEN_PARTNER
      - DRAGON_ACCESS_KEY
      - DRAGON_SECRET_ACCESS_KEY

  deployment:
    image: cd.docker-registry.corp.yahoo.co.jp:4443/approduce/hosted-danger-sd-image:latest
    requires: [publish-image]
    steps:
      - confirmation: |
          echo "Deploying image: "
          echo `meta get fixed_docker_image`
      - deployment: |
          sed -e "s@IMAGE@"`meta get fixed_docker_image`"@g" ops/kube/deployment.yaml.tmpl > deployment.yaml
          wget https://raw.ghe.corp.yahoo.co.jp/approduce/hosted-danger-secrets/master/config?token=$WGET_TOKEN -O config -q
          kubectl apply -f deployment.yaml --kubeconfig config --namespace=default
    secrets:
      - WGET_TOKEN
  acceptance-test:
    image: cd.docker-registry.corp.yahoo.co.jp:4443/approduce/hosted-danger-sd-image:latest
    requires: [deployment]
    steps:
      - wait_deployment: |
          echo "Wait the deployment, sleeping 60 sec..."
          sleep 60
      - setup-test: |
          mkdir wd && cd wd && git clone https://ghe.corp.yahoo.co.jp/approduce/hosted-danger-acceptance-tests.git
          cd hosted-danger-acceptance-tests
      - default: |
          pwd
          ls -la
          git reset --hard origin/default
          rm -f update && echo `date` > update
          git add update
          git commit -m "[skip ci] `date`"
          git push origin default
      - ruby-default: |
          git reset --hard origin/ruby-default
          rm -f update && echo `date` > update
          git add update
          git commit -m "[skip ci] `date`"
          git push origin ruby-default
      - ruby-bundler: |
          git reset --hard origin/ruby-bundler
          rm -f update && echo `date` > update
          git add update
          git commit -m "[skip ci] `date`"
          git push origin ruby-bundler
      - js-system: |
          git reset --hard origin/js-system
          rm -f update && echo `date` > update
          git add update
          git commit -m "[skip ci] `date`"
          git push origin js-system
      - js-npm: |
          git reset --hard origin/js-npm
          rm -f update && echo `date` > update
          git add update
          git commit -m "[skip ci] `date`"
          git push origin js-npm
      - js-yarn: |
          git reset --hard origin/js-yarn
          rm -f update && echo `date` > update
          git add update
          git commit -m "[skip ci] `date`"
          git push origin js-yarn
