apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hd-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hd-service
          servicePort: 80
