apiVersion: v1
kind: Service
metadata:
  name: hd-service
spec:
  selector:
    app: hd-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
  - protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 9100
  type: NodePort
