kind: ConfigMap
apiVersion: v1
metadata:
  name: alert-rules
  namespace: monitoring
data:
  rules.yaml: |-
    groups:
      - name: node
        rules:
          - alert: InstanceUp
            expr: up == 1
            for: 1m
            labels:
              severity: default
            annotations:
              summary: "Just for testing"
              description: "Just for testing, the instance is healthy."
