kind: ConfigMap
apiVersion: v1
metadata:
  name: mym-template
  namespace: monitoring
data:
  mym.tmpl: |-
    {{ define "mym.template" }}
    @all

    summary: {{ .Annotations.summary }}
    app: {{ .GroupLabels.app }}
    {{ .Labels.instance }}
    {{ end }}
